name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: docs/yarn.lock

      - name: Install and Build
        working-directory: ./docs
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy to External Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: dtychshenko/dtychshenko.github.io
          publish_branch: gh-pages
          publish_dir: ./docs/build
          destination_dir: peppermint
          keep_files: false
